version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      WATCHTOWER_MONITOR_ONLY: 'true'
      WATCHTOWER_NOTIFICATIONS: "email slack"
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: paul@example.com
      WATCHTOWER_NOTIFICATION_EMAIL_TO: paul@example.net
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: smtp.example.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 25
#      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: your_gmail
#      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: gmail_app_password
      WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: "https://hooks.slack.com/services/<code here>"
      WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER: watchtower
      WATCHTOWER_NOTIFICATION_SLACK_CHANNEL: #docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
