version: "2.1"
services:
  wireguard:
   image: lscr.io/linuxserver/wireguard
   container_name: wireguard
   cap_add:
     - NET_ADMIN
     - SYS_MODULE
   environment:
     - PUID=1000
     - PGID=1000
     - TZ=Europe/London
     - SERVERURL=vpn.example.com # domain optional, public IP is required at least
     - SERVERPORT=51820
     - PEERS=host01,host02,host03,host04,host05,host06,host07,host08,host09
     - PEERDNS=10.1.1.25, 10.1.1.26 # optional
     - INTERNAL_SUBNET=10.1.2.0 # optional
     - ALLOWEDIPS=10.1.1.0/24 # optional
   volumes:
     - /srv/wireguard/config:/config
     - /lib/modules:/lib/modules
   ports:
     - 51820:51820/udp
   sysctls:
     - net.ipv4.conf.all.src_valid_mark=1
   restart: unless-stopped
